# Azure DevOps Pipeline for Next.js Azure Static Web App
# Builds and deploys the app on push to main

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Use Node.js 18.x'

- script: npm ci
  displayName: 'Install dependencies'

- script: npm run build
  displayName: 'Build Next.js app'

- task: AzureStaticWebApp@0
  inputs:
    app_location: '/'
    output_location: '.next'
    azure_static_web_apps_api_token: $(deployment_token) # Set this as a pipeline secret variable
  displayName: 'Deploy to Azure Static Web Apps'
